rails generate scaffold Bug code:string product:string component:string version:string summary:string description:string hardware:string importance:integer targetmilestone:string assignedto:string qacontact:string url:string whiteboard:string keywords:string tags:string dependson:string blocks:string origestimated:float hoursworked:float hoursleft:float deadline:date additionalcomments:string status:string -f
rails generate scaffold Bugzillaproduct code:string product:string description:string openforbugentry:boolean enableunconfirmedstatus:boolean maxvotesperperson:integer maxvotespersonperbug:integer confirmbugsvotes:integer version:string createchartdatasets:boolean component:string componentdescription:string defaultassignee:string defaultcclist:string -f
rails generate scaffold Bugzillauser loginname:string realname:string password:string bugmaildisabled:boolean disabletext:string adminpermission:boolean creategroupspermission:boolean edituserspermission:boolean -f
rails generate scaffold Campaign code:string owner:string name:string active:boolean type:string status:string start:date end:date expectedrevenue:integer budgetedcost:integer actualcost:integer expectedresponse:float numsent:integer parentcampaign:string -f
rails generate scaffold Course code:string fullname:string shortname:string courseidnumber:integer summary:string format:string numberofweekstopics:integer start:date hiddensections:string newsitemstoshow:integer showgrades:boolean showactivityreports:boolean maxuploadsize:integer defaultroles:string -f
rails generate scaffold Issue code:string project:string issuetype:string summary:string storypoints:integer priority:string duedate:date components:string affectsversions:string fixversions:string assignee:string environment:string description:string labels:string epic:string sprint:string -f
rails generate scaffold Lead code:string owner:string firstname:string lastname:string company:string title:string status:string phone:string email:string street:string city:string state:string zipcode:string county:string website:string numberofemployees:integer annualrevenue:integer source:string industry:string description:string -f
rails generate scaffold Product code:string name:string model:string sku:string weight:float manufacturer:string status:string taxclass:string urlkey:string visibility:string setproductasnewfromdate:date setproductasnewtodate:date countryofmanufacture:string price:float cost:float specialprice:float specialpricefromdate:date specialpricetodate:date applymap:string displayactualprice:float suggestedretailprice:float metatitle:string metakeywords:string metadescription:string shortdescription:string description:string indepth:string dimensions:string activationinformation:string color:string customdesign:string activefrom:date activeto:date customlayoutupdate:string displayproductoptionsin:string pagelayout:string enablerecurringprofile:boolean allowgiftmessage:boolean managestock:boolean qty:float qtyforitemsstatustobecomeoutofstock:float minimumqtyallowedinshoppingcart:float maximumqtyallowedinshoppingcart:float qtyusesdecimals:boolean backorders:string notifyforquantitybelow:float enableqtyincrements:boolean stockavailability:boolean tags:string -f
rails generate scaffold Project name:string description:string identifier:string homepage:string public:boolean subprojectof:string bugtracker:boolean featuretracker:boolean supporttracker:boolean -f
rails generate scaffold Quiz code:string name:string description:string displaydescription:boolean open:datetime close:datetime timelimit:integer whentimeexpires:string submissiongraceperiod:integer gradecategory:string attemptsallowed:string gradingmethod:string -f
rails generate scaffold Salesforceuser name:string alias:string email:string username:string communitynickname:string title:string company:string department:string division:string address:string timezone:string locale:string language:string delegatedapprover:string manager:string role:string userlicense:string profile:string active:boolean marketinguser:boolean offlineuser:boolean knowledgeuser:boolean forcecomflowuser:boolean serviceclouduser:boolean sitecomcontributoruser:boolean sitecompublisheruser:boolean mobileuser:boolean -f
rails generate scaffold Testcase code:string title:string summary:string preconditions:string status:string importance:string minutes:integer -f
